-- 1. Initialize Enforcement Extensions if required for scaling vectors
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Client Accounts Table Profile (Manages Tier Allocation Metrics)
CREATE TABLE IF NOT EXISTS agency_clients (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_name VARCHAR(255) NOT NULL CHECK (length(trim(company_name)) >= 2),
    industry VARCHAR(255) NOT NULL,
    target_audience TEXT NOT NULL,
    subscription_tier VARCHAR(50) NOT NULL DEFAULT 'freemium' CHECK (subscription_tier IN ('free', 'freemium', 'premium')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Human-In-The-Loop Task Gatekeeper Matrix (Captures paused automated states)
CREATE TABLE IF NOT EXISTS hitl_automation_gates (
    task_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    client_id UUID REFERENCES agency_clients(id) ON DELETE CASCADE,
    target_module VARCHAR(100) NOT NULL CHECK (target_module IN ('core_orchestrator', 'branding_studio', 'design_studio', 'marketing_studio')),
    current_status VARCHAR(50) NOT NULL DEFAULT 'AWAITING_REVIEW' CHECK (current_status IN ('AWAITING_REVIEW', 'APPROVED_BY_HUMAN', 'REJECTED_HEALING_REQUIRED')),
    captured_payload_json JSONB NOT NULL,
    error_exception_trace TEXT,
    last_modified_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Unified Asset Distribution Manifest (Tracks URLs and dimensions generated by studios)
CREATE TABLE IF NOT EXISTS studio_generated_assets (
    asset_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    client_id UUID REFERENCES agency_clients(id) ON DELETE CASCADE,
    asset_type VARCHAR(100) NOT NULL, -- e.g., 'BRAND_GUIDE', 'LOGO_VECTOR', 'AD_COPY_BLOCK'
    cdn_delivery_url TEXT NOT NULL,
    dimension_profile VARCHAR(20) DEFAULT '1:1',
    is_live_distributed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Performance Speed Indexes for fast client workspace searches
CREATE INDEX IF NOT EXISTS idx_clients_tier ON agency_clients(subscription_tier);
CREATE INDEX IF NOT EXISTS idx_hitl_status ON hitl_automation_gates(current_status);
CREATE INDEX IF NOT EXISTS idx_assets_client ON studio_generated_assets(client_id);
